# Generated by Django 5.2.3 on 2025-07-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_category_organisaton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organisaton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
